import {COMPANY_IDS} from './region-data-v12.js';
import {CITIES,distance} from './data-v12.js';
import {ROADS,roadBetween} from './land-data-v12.js';
import {shipSpec} from './industry-v12.js';
import {entry,routeLegs} from './engine-v12.js';
const check=(ok,message)=>{if(!ok)throw new Error(message);};
const amount=n=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=1e12;
export function initializeRoads(w){w.roads=Object.fromEntries(Object.keys(ROADS).map(id=>[id,{owner:id==='nantes_paris'?'private':'state',basis:0,quality:0,security:0,invested:0,dailyRoad:0,dailySecurity:0,tollPool:0}]));}
export function travelDistance(s,type,a,b){return shipSpec(s,type)?.mode==='land'?(roadBetween(a,b)?.[1].km??Infinity):distance(a,b);}
export function canServe(s,type,r){const spec=shipSpec(s,type);return Boolean(spec)&&spec.mode===(r.mode??'sea')&&routeLegs(r).every(([a,b])=>travelDistance(s,type,a,b)<=spec.range);}
export function routeNations(r){return [...new Set([...r.stops.map(id=>CITIES[id].nation),...(r.mode==='land'?routeLegs(r).flatMap(([a,b])=>roadBetween(a,b)?.[1].nations??[]):[])])];}
export function roadDays(s,type,a,b,quality){const link=roadBetween(a,b);if(!link)return Infinity;const [id,r]=link,q=quality??s.world.roads[id].quality,improvement=q/(5+q);return Math.ceil(r.km/(shipSpec(s,type).speed*(r.penalty+(1-r.penalty)*.6*improvement)*(1+improvement)));}
export function roadToll(s,a,b){const link=roadBetween(a,b);if(!link)return 0;const [id,r]=link,d=s.world.roads[id];if(d.owner===s.industry.id)return 0;const factor=r.nations.reduce((sum,n)=>sum+1+(60-(s.world.enabled?s.diplomacy.friendship[n]:60))/100,0)/r.nations.length;return r.km*.02*factor;}
export function payRoadToll(s,r,a,b){if(r.mode!=='land')return 0;const cost=roadToll(s,a,b),[id]=roadBetween(a,b),d=s.world.roads[id];if(cost){entry(s,'roadToll',-cost,r.id,{road:id});r.transport.costs+=cost;if(!['state','private'].includes(d.owner))d.tollPool+=cost*.2;}return cost;}
export function roadSafety(s,a,b){const [id,r]=roadBetween(a,b),d=s.world.roads[id];return r.safety+(1-r.safety)*.9*d.security/(5+d.security);}
export function roadRisk(s,r,a,b){const safety=roadSafety(s,a,b),defense=1+r.escorts*.8;return {daily:s.world.enabled?(1-safety)*.015/defense:0,lossFraction:.6/defense,sinkChance:.02/defense,hostile:false};}
export function roadQuote(s,id){const r=ROADS[id],d=s.world.roads[id];check(r&&d,'道路を確認してください。');return {cost:Math.ceil((500+r.km*2)*(1+.1*d.quality)*(d.owner==='state'?1:1.5)),eligible:d.owner!==s.industry.id&&r.nations.every(n=>s.licenses.includes(n)),owner:d.owner};}
export function buyRoadRight(root,id,buyer=root){check(!buyer.gameOver,'破産後は操作できません。新しいゲームを開始してください。');const q=roadQuote(buyer,id),d=buyer.world.roads[id];check(q.eligible,'道路の通過国すべての交易免許が必要です。');check(buyer.cash>=q.cost,'道路開発権の資金が不足しています。');const seller=[root,...root.competitors].find(c=>c.industry.id===d.owner);check(['state','private'].includes(d.owner)||seller,'開発権の所有者を確認してください。');entry(buyer,'roadPurchase',-q.cost,null,{road:id});if(seller){entry(seller,'roadSale',q.cost+d.tollPool,null,{road:id});seller.gameOver=seller.cash<0;}Object.assign(d,{owner:buyer.industry.id,basis:q.cost,dailyRoad:0,dailySecurity:0,tollPool:0});}
export function setRoadInvestment(s,id,road,security){const d=s.world.roads[id];check(!s.gameOver&&d?.owner===s.industry.id&&amount(road)&&amount(security)&&amount(road+security),'道路の権利・投資額を確認してください。');d.dailyRoad=road;d.dailySecurity=security;}
export function roadDaily(s){return Object.values(s.world.roads).filter(d=>d.owner===s.industry.id).reduce((n,d)=>n+d.dailyRoad+d.dailySecurity,0);}
export function roadAssets(s){return Object.values(s.world.roads).filter(d=>d.owner===s.industry.id).reduce((n,d)=>n+d.basis+d.tollPool,0);}
export function advanceRoads(s){for(const [id,d]of Object.entries(s.world.roads))if(d.owner===s.industry.id){if(d.tollPool){entry(s,'roadIncome',d.tollPool,null,{road:id});d.tollPool=0;}for(const [kind,key]of [['quality','dailyRoad'],['security','dailySecurity']]){const value=d[key];if(value>0&&s.cash>=value){entry(s,'roadInvestment',-value,null,{road:id});d.invested+=value;d[kind]+=Math.sqrt(value)/150/(1+d[kind]/5);}}}}
export function confiscateRoads(s,nation){for(const [id,d]of Object.entries(s.world.roads))if(d.owner===s.industry.id&&ROADS[id].nations.includes(nation))Object.assign(d,{owner:'state',basis:0,quality:0,security:0,invested:0,dailyRoad:0,dailySecurity:0,tollPool:0});}
export function transferRoads(buyer,seller){for(const d of Object.values(buyer.world.roads))if(d.owner===seller.industry.id){d.owner=buyer.industry.id;d.dailyRoad=0;d.dailySecurity=0;}}
export function validateLand(s,nested){const roads=s.world.roads;check(roads&&Object.keys(roads).length===Object.keys(ROADS).length&&Object.keys(ROADS).every(id=>Object.hasOwn(roads,id)),'道路データが不正です。');for(const [id,d]of Object.entries(roads)){check(d&&['state','private','player',...COMPANY_IDS].includes(d.owner)&&['basis','quality','security','invested','dailyRoad','dailySecurity','tollPool'].every(k=>amount(d[k])),'道路データが不正です。');if(d.owner===s.industry.id)check(ROADS[id].nations.every(n=>s.licenses.includes(n)),'道路の免許が不正です。');}if(!nested){const ids=[s,...s.competitors].map(c=>c.industry.id);check(Object.values(roads).every(d=>['state','private',...ids].includes(d.owner)),'道路の所有者が不正です。');}}
