import {execFileSync} from 'node:child_process';
import {mkdirSync,copyFileSync,writeFileSync,readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
execFileSync(process.execPath,['scripts/export-wasm-data.mjs'],{stdio:'inherit'});
execFileSync('cargo',['build','--manifest-path','wasm-core/Cargo.toml','--target','wasm32-unknown-unknown','--release','--locked'],{stdio:'inherit'});
mkdirSync('assets/wasm',{recursive:true});
copyFileSync('wasm-core/target/wasm32-unknown-unknown/release/sails_flags_core.wasm','assets/wasm/engine.wasm');
const files=['wasm-core/Cargo.toml','wasm-core/Cargo.lock','wasm-core/data/world.json',...readdirSync('wasm-core/src').filter(f=>f.endsWith('.rs')).map(f=>'wasm-core/src/'+f)].sort();
const hash=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
const sourceHash=file=>createHash('sha256').update(readFileSync(file,'utf8').replace(/^\uFEFF/,'').replace(/\r\n/g,'\n')).digest('hex');
writeFileSync('assets/wasm/build.json',JSON.stringify({version:'3.3.9',binary:hash('assets/wasm/engine.wasm'),sources:Object.fromEntries(files.map(f=>[f,sourceHash(f)]))},null,2)+'\n');
