// Presentation only. IDs, coordinates and saved route endpoints never change.
// ID -> Latin, Japanese, Simplified Chinese, Traditional Chinese, Korean.
export const cityNames = {
 beijing:['Beijing','北京','北京','北京','베이징'],
 xian:["Xi’an",'西安','西安','西安','시안'],
 nanjing:['Nanjing','南京','南京','南京','난징'],
 suzhou:['Suzhou','蘇州','苏州','蘇州','쑤저우'],
 hangzhou:['Hangzhou','杭州','杭州','杭州','항저우'],
 jingdezhen:['Jingdezhen','景徳鎮','景德镇','景德鎮','징더전'],
 hankou:['Hankou','漢口','汉口','漢口','한커우'],
 changsha:['Changsha','長沙','长沙','長沙','창사'],
 kyoto:['Kyoto','京都','京都','京都','교토'],
 hanseong:['Hanseong','漢城','汉城','漢城','한성'],
 guangzhou:['Guangzhou','広州','广州','廣州','광저우'],
 xiamen:['Xiamen','厦門','厦门','廈門','샤먼'],
 ningbo:['Ningbo','寧波','宁波','寧波','닝보'],
 nagasaki:['Nagasaki','長崎','长崎','長崎','나가사키'],
 osaka:['Osaka','大阪','大阪','大阪','오사카'],
 busan:['Busan','釜山','釜山','釜山','부산'],
 edo:['Edo','江戸','江户','江戶','에도'],
 urga:['Urga','庫倫','库伦','庫倫','우르가'],
 kalgan:['Kalgan','張家口','张家口','張家口','장자커우'],
 pyongyang:['Pyongyang','平壌','平壤','平壤','평양'],
 tianjin:['Tianjin','天津','天津','天津','톈진'],
 jinan:['Jinan','済南','济南','濟南','지난'],
 taiyuan:['Taiyuan','太原','太原','太原','타이위안'],
 kaifeng:['Kaifeng','開封','开封','開封','카이펑'],
 yangzhou:['Yangzhou','揚州','扬州','揚州','양저우'],
 nanchang:['Nanchang','南昌','南昌','南昌','난창'],
 fuzhou:['Fuzhou','福州','福州','福州','푸저우'],
 foshan:['Foshan','仏山','佛山','佛山','포산'],
 yichang:['Yichang','宜昌','宜昌','宜昌','이창'],
 chongqing:['Chongqing','重慶','重庆','重慶','충칭'],
 chengdu:['Chengdu','成都','成都','成都','청두'],
 kunming:['Kunming','昆明','昆明','昆明','쿤밍'],
 hami:['Hami','哈密','哈密','哈密','하미'],
 jiuquan:['Jiuquan','酒泉','酒泉','酒泉','주취안'],
 zhangye:['Zhangye','張掖','张掖','張掖','장예'],
 wuwei:['Wuwei','武威','武威','武威','우웨이'],
 lanzhou:['Lanzhou','蘭州','兰州','蘭州','란저우'],
 shanhaiguan:['Shanhaiguan','山海関','山海关','山海關','산하이관'],
 jinzhou:['Jinzhou','錦州','锦州','錦州','진저우'],
 shenyang:['Shenyang','瀋陽','沈阳','瀋陽','선양'],
 liaoyang:['Liaoyang','遼陽','辽阳','遼陽','랴오양'],
 fenghuangcheng:['Fenghuangcheng','鳳凰城','凤凰城','鳳凰城','펑황청'],
 uiju:['Uiju','義州','义州','義州','의주'],
 kaesong:['Kaesong','開城','开城','開城','개성'],
 jilin:['Jilin','吉林','吉林','吉林','지린'],
 ningguta:['Ningguta','寧古塔','宁古塔','寧古塔','닝구타'],
 nagoya:['Nagoya','名古屋','名古屋','名古屋','나고야'],
 sunpu:['Sunpu','駿府','骏府','駿府','슨푸'],
 hiroshima:['Hiroshima','広島','广岛','廣島','히로시마'],
 hakata:['Hakata','博多','博多','博多','하카타'],
 kanazawa:['Kanazawa','金沢','金泽','金澤','가나자와'],
 sendai:['Sendai','仙台','仙台','仙台','센다이'],
};
export function localizedCityName(city,language='en') {
 const names=cityNames[city.id];
 return names?.[({ja:1,'zh-CN':2,'zh-TW':3,ko:4})[language]??0]??city.mapName??city.nameEn??city.name??city.id;
}
