import {shipCatalog,shipSpec} from './industry.js';
import {quoteFleetReplacement} from './fleet.js';
import {shipName,escapeName} from './identity.js';
import {tx,t,nameOf,errorMessage} from './i18n.js';
export function renderFleet(s){return `<section class="panel" id="fleet-panel"><h2>${tx('船団管理','Fleet management')}</h2><div class="buttons"><button data-action="replace-types" ${s.gameOver||!s.ships.length?'disabled':''}>${tx('船種をまとめて置換','Replace a ship type')}</button><button data-action="replace-automation" ${s.gameOver||!s.routes.length?'disabled':''}>${tx('自動増減の船種をまとめて変更','Replace automation types')}</button></div><details id="fleet-names"><summary>${tx('保有船と船名','Owned ships and names')} (${s.ships.length})</summary><ul class="fleet-list">${s.ships.map(v=>`<li><strong>${escapeName(shipName(s,v))}</strong> · ${nameOf(shipSpec(s,v.type))} #${v.id.split('-')[1]} · ${v.routeId?tx('配属中','Assigned'):tx('未使用','Idle')} <button data-action="rename-ship" data-id="${v.id}">${tx('船名を変更','Rename ship')}</button></li>`).join('')||`<li>${tx('保有船はありません。','No ships owned.')}</li>`}</ul></details></section>`;}
export function renderReplacement(s,draft,{cash}){
 const q=quoteFleetReplacement(s,draft),catalog=Object.entries(shipCatalog(s)),options=selected=>catalog.map(([id,spec])=>`<option value="${id}" ${id===selected?'selected':''}>${nameOf(spec)}</option>`).join('');
 const title=draft.mode==='automation'?tx('自動増減設定の一括変更','Replace automation settings'):draft.mode==='route'?tx('このルートの全船を置換','Replace every ship on this route'):tx('船種の一括置換','Replace a ship type');
 return `<dialog aria-labelledby="fleet-replacement-title"><h2 id="fleet-replacement-title">${title}</h2><form id="fleet-replacement-form">${draft.mode==='route'?'':`<label>${tx('置換元の船種','Source ship type')}<select name="source">${options(draft.source)}</select></label>`}<label>${tx('置換先の船種','Target ship type')}<select name="target">${options(draft.target)}</select></label><p>${tx('対象','Affected')}: <b>${q.count}</b> ${draft.mode==='automation'?tx('ルート','routes'):tx('隻','ships')} · ${tx('関係するルート','Routes involved')}: ${q.routeIds.length}</p>${draft.mode==='automation'?`<p class="small muted">${tx('船の売買は行わず、該当する全ルートの自動増減用船種だけを変更します。喪失船の補充待ちは元の船種を維持します。','Only automation type settings change; no ships are traded. Existing lost-ship claims keep their original types.')}</p>`:`<dl><dt>${tx('旧船の売却額','Sale proceeds')}</dt><dd>${cash(q.sale)}</dd><dt>${tx('新船の購入・建造額','Purchase / construction')}</dt><dd>${cash(q.purchase)}</dd><dt>${q.cost<0?tx('差額の受取額','Net proceeds'):tx('必要な差額','Net payment')}</dt><dd>${cash(Math.abs(q.cost))}</dd><dt>${tx('置換後の保有資金','Cash after replacement')}</dt><dd>${cash(q.remaining)}</dd></dl><p class="small muted">${tx('旧船は現在の船種価格で売却します。船名・積み荷・目的地・残日数を維持し、新しい積載量と速度は次の出港から使用します。維持費・武装は直ちに変更します。置換済み船種は対象外です。自動増減設定は別の操作で変更できます。','Old ships sell at their current type price. Names, cargo, destinations and remaining travel time are preserved; new capacity and speed apply at the next departure. Upkeep and armament change immediately. Ships already of the target type are skipped. Change automation settings separately.')}</p><p>${tx('航行中の対象船','Affected ships at sea')}: ${q.sailing}</p>`}${q.error?`<p class="warning" role="status">${escapeName(errorMessage(new Error(q.error)))}</p>`:''}<div class="buttons"><button type="button" data-action="cancel">${t('cancel')}</button><button class="primary" ${q.error?'disabled':''}>${tx('この内容で一括置換','Confirm replacement')}</button></div></form></dialog>`;
}
export function renderRename(edit){const label=edit.kind==='company'?tx('会社名','Company name'):edit.kind==='design'?tx('船種名','Design name'):tx('船名','Ship name');return `<dialog aria-labelledby="rename-title"><h2 id="rename-title">${label} · ${tx('変更','Rename')}</h2><form id="rename-form"><label>${label}<input name="name" value="${escapeName(edit.value)}" maxlength="80" required autofocus></label><p class="small muted">${tx('1～80文字。名前の重複は可能です。','1–80 characters. Duplicate names are allowed.')}</p><div class="buttons"><button type="button" data-action="cancel">${t('cancel')}</button><button>${tx('名前を保存','Save name')}</button></div></form></dialog>`;}
