import {productionDevelopment,totalProductionBudget} from './production-investment.js';
import {renderProductionInvestment} from './production-view.js';
import {RETIRED_CITIES} from './retired-network.js';
import {CITIES,SHIPS} from './data.js';
import {shipCatalog,shipSpec,shipDaily,HULLS,HULL_LEVELS,YARD_COST,designQuote,developmentQuote,marketFactors,industryDaily,DESIGN_BUDGET_KEYS} from './industry.js';
import {tx,t,nameOf} from './i18n.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const initialDesign=()=>({hull:'sloop',...Object.fromEntries(DESIGN_BUDGET_KEYS.map(k=>[k,0]))});
export function renderIndustry(s,{cash,decimal},draft=initialDesign()){
 const i=s.industry,disabled=s.gameOver?'disabled':'';
 const stats=spec=>`${tx('積載','Capacity')} ${spec.capacity} · ${tx('速度','Speed')} ${decimal(spec.speed)} · ${tx('砲門','Guns')} ${decimal(spec.guns)} · ${tx('航続','Range')} ${decimal(spec.range)} nm`;
 return `<section class="panel" id="industry-panel"><h2>${tx('技術と造船','Technology and shipbuilding')}</h2><p class="small muted">${tx('日額0で停止。投資効果は逓減し、資金不足ならその日の支出を見送ります。技術・研究・都市投資は資産ランキングに加算しません。','Set daily amounts to 0 to stop. Returns diminish; unaffordable investments are skipped. Technology, research and city investment are excluded from assets.')}</p>
 <form id="technology-form"><div class="form-row">${['shipbuilding','seafaring'].map(k=>`<label>${k==='shipbuilding'?tx('造船技術','Shipbuilding technology'):tx('海上交易技術','Seafaring technology')} ${decimal(i.technology[k])}<br>${tx('継続投資（日額）','Daily investment')}<input type="number" name="${k}" value="${i.investment[k]}" min="0" step="any" required ${disabled}></label>`).join('')}</div><button ${disabled}>${tx('技術投資を適用','Apply technology investment')}</button></form>
 <p class="small">${tx('海上交易技術による船の維持費軽減','Ship upkeep reduction from seafaring technology')}: ${decimal(25*i.technology.seafaring/(50+i.technology.seafaring))}% · ${tx('技術・都市への継続支出合計','Total daily technology and city commitments')}: ${cash(industryDaily(s))}</p>
 <details id="ship-design"><summary>${tx('造船設備と設計研究','Shipyard and design research')}</summary><p>${i.shipyard?tx('造船設備：保有','Shipyard: owned'):tx('造船技術5で設備を購入できます。設備は会社保有で所在地を持ちません。','Buy a company shipyard at shipbuilding technology 5. It has no location.')}</p>${!i.shipyard?`<button data-action="buy-yard" ${disabled||i.technology.shipbuilding<5||s.cash<YARD_COST?'disabled':''}>${tx('造船設備を取得','Buy shipyard')} · ${cash(YARD_COST)}</button>`:''}
 <form id="design-form"><label>${tx('基本船型','Base hull')}<select name="hull" ${disabled}>${Object.entries(HULLS).map(([id,h])=>`<option value="${id}" ${draft.hull===id?'selected':''}>${nameOf(h)} · ${tx('必要技術','Required technology')} ${HULL_LEVELS[id]}</option>`).join('')}</select></label><div class="form-row">${DESIGN_BUDGET_KEYS.map(k=>`<label>${({cargo:tx('積載の設計予算（¤）','Cargo design budget (¤)'),speed:tx('速度の設計予算（¤）','Speed design budget (¤)'),guns:tx('武装の設計予算（¤）','Armament design budget (¤)'),range:tx('航続距離の設計予算（¤）','Range design budget (¤)'),upkeep:tx('維持費改善の設計予算（¤）','Upkeep improvement budget (¤)')})[k]}<input type="number" name="${k}" value="${draft[k]}" min="0" step="any" required ${disabled}></label>`).join('')}</div><p class="small muted">${tx('各項目に研究時に支払う予算額を指定します。増額の効果は逓減します。積載増は減速、速度・武装増は積載減を伴います。航続投資は航続距離を延ばし、維持費改善は整備効率を高めます。建造費・維持費は完成性能から算出します。研究後の設計は固定です。','Enter one-time research budgets with diminishing benefits. Cargo slows ships; speed and armament reduce capacity. Range investment extends endurance; upkeep investment improves servicing efficiency. Construction and upkeep depend on final performance. Researched designs are fixed.')}</p><div id="design-quote">${renderDesignEstimate(s,draft,{cash,decimal})}</div></form>
 <h3>${tx('研究済み設計','Researched designs')}</h3>${i.designIds.map(id=>{const spec=shipSpec(s,id);return `<article class="design-card"><strong>${nameOf(spec)}</strong> <button data-action="rename-design" data-id="${id}">${tx('船種名を変更','Rename design')}</button><p>${stats(spec)}<br>${tx('建造費 / 実効維持費','Construction / effective upkeep')}: ${cash(spec.price)} / ${cash(shipDaily(s,id))} ${t('daily')}</p><button data-action="buy" data-id="${id}" ${disabled||!i.shipyard||s.cash<spec.price?'disabled':''}>${tx('この設計で1隻建造','Build one ship')}</button></article>`;}).join('')||`<p class="muted">${tx('研究済みの設計はありません。','No researched designs yet.')}</p>`}<p class="small muted">${tx('研究済み設計は、新規ルートと自動増減用の船種にも指定できます。','Researched designs are also available for route opening and automation.')}</p></details>
 <h3>${tx('都市の継続投資一覧','Ongoing city investments')}</h3>${Object.entries(s.world.development).filter(([,d])=>d.owner===i.id).map(([city,d])=>`<p>${nameOf(CITIES[city])} · ${tx('規模 / 生産（日額）','Size / production per day')}: ${cash(d.dailySize)} / ${cash(totalProductionBudget(d))} <button data-action="city-development" data-id="${city}">${tx('変更・停止','Change / stop')}</button></p>`).join('')||`<p class="muted">${tx('都市開発権は市場画面で取得できます。','Buy development rights in the port market panel.')}</p>`}
 <details id="investment-history"><summary>${tx('設備・権利・投資の履歴','Facilities, rights and investment history')}</summary><ol class="management-log">${[...i.log].reverse().map(e=>`<li>${e.day} ${t('dayUnit')} · ${({shipyard:tx('造船設備を取得','Shipyard purchased'),research:tx('設計研究','Design researched'),sold:tx('開発権を売却','Development right sold'),right:tx('開発権を取得','Development right purchased'),confiscated:tx('開発権と投資を無補償没収','Right and investment confiscated without compensation'),skipped:tx('資金不足で投資を見送り','Investment skipped: insufficient funds')})[e.kind]}${e.city?' · '+nameOf(CITIES[e.city]??RETIRED_CITIES[e.city]):''}${e.cost?' · '+cash(e.cost):''}</li>`).join('')||`<li>${tx('まだ記録はありません。','No entries yet.')}</li>`}</ol></details></section>`;
}
export function renderDevelopment(s,city,{cash,decimal}){
 const d=s.world.development[city],q=developmentQuote(s,city),owned=d.owner===s.industry.id,owner=owned?(s.companyName??tx('自社','Your company')):d.owner==='state'?tx('国家','State'):d.owner==='private'?tx('既存の民間所有者','Private owner'):s.competitors.find(c=>c.industry.id===d.owner)?.name??tx('他社','Other company');
 const f=marketFactors(s,city,'rum');
 return `<section class="development-panel"><h3>${tx('都市開発','City development')} · ${nameOf(CITIES[city])}</h3><p>${tx('開発権の所有者','Right owner')}: ${escape(owner)}<br>${tx('規模 / 生産開発','Size / production development')}: ${decimal(d.size)} / ${decimal(productionDevelopment(d))} · ${tx('需要倍率','Demand multiplier')}: ${decimal(f.demand)}×</p><p class="small muted">${tx('都市規模は需要を増やします。生産投資は品目ごとの適性に依存します。税収は補助収入です。','City size increases demand. Production investment depends on each commodity’s local suitability. Taxes provide supplemental income.')}</p>
 ${owned?`<form class="city-investment-form" id="development-${city}" data-development-city="${city}"><div class="form-row"><label>${tx('規模投資（日額）','Size investment per day')}<input type="number" name="size" min="0" step="any" value="${d.dailySize}" required></label></div>${renderProductionInvestment(s,city,cash)}<button ${s.gameOver?'disabled':''}>${tx('都市投資を適用','Apply city investment')}</button></form><p class="small">${tx('取得原価 / 累計開発投資','Right cost basis / cumulative development investment')}: ${cash(d.basis)} / ${cash(d.invested)}<br>${tx('基礎税収（日額）','Base tax income per day')}: ${cash(.15+.35*d.size/(5+d.size))} + ${tx('実際の交易税の15%','15% of actual trade taxes')}</p>`:`<p>${tx('開発権取得費','Right purchase price')}: <b>${cash(q.cost)}</b> · ${tx('取得後の資金','Cash after purchase')}: ${cash(s.cash-q.cost)}</p><button data-action="buy-right" data-id="${city}" ${s.gameOver||!q.eligible||s.cash<q.cost?'disabled':''}>${tx('開発権を取得','Buy development right')}</button>${!q.eligible?`<p>${tx('この国の交易免許が必要です。','A trading license for this nation is required.')}</p>`:''}`}
 <p class="small muted">${tx('日額0で投資停止。免許取消時は権利と投資が無補償で没収されます。権利は取得原価、設備は購入額で資産評価し、開発・研究の支出は加算しません。','Set daily amounts to 0 to stop. License revocation confiscates rights and investment without compensation. Rights and facilities count at cost; development and research spending do not.')}</p></section>`;
}

export function renderDesignEstimate(s,draft,{cash,decimal}){
 const q=designQuote(s,draft.hull,draft),p=q.spec,effective=p.daily*(1-.25*s.industry.technology.seafaring/(50+s.industry.technology.seafaring));
 return `<p>${tx('積載','Capacity')} ${p.capacity} · ${tx('速度','Speed')} ${decimal(p.speed)} · ${tx('砲門','Guns')} ${decimal(p.guns)} · ${tx('航続','Range')} ${decimal(p.range)} nm<br>${tx('整備効率による維持費軽減','Upkeep reduction from servicing efficiency')}: ${decimal(p.maintenanceEfficiency*100)}%</p><p>${tx('基本研究費＋設計予算合計＝研究時の支払額','Base research + total design budgets = payment at research')}: ${cash(q.baseResearchCost)} + ${cash(q.budgetTotal)} = <b>${cash(q.researchCost)}</b><br>${tx('研究後の保有資金','Cash after research')}: ${cash(s.cash-q.researchCost)}</p><p>${tx('1隻の建造費 / 基準維持費 / 技術反映後の維持費','Construction per ship / base upkeep / upkeep after technology')}: ${cash(p.price)} / ${cash(p.daily)} ${t('daily')} / ${cash(effective)} ${t('daily')}</p><button ${s.gameOver||!q.eligible||s.cash<q.researchCost?'disabled':''}>${tx('この設計を研究','Research this design')} · ${cash(q.researchCost)}</button>${s.cash<q.researchCost?`<p class="warning">${tx('研究資金が不足しています。','Insufficient research funds.')}</p>`:''}${!q.eligible?`<p class="small muted">${tx('造船設備と船型の必要技術を満たしてください。','Requires a shipyard and the hull technology.')}</p>`:''}`;
}
