import {ROAD_REGIONS} from './continental-data.js';
import {RETIRED_CITIES,RETIRED_ROADS} from './retired-network.js';
import {ROADS,roadBetween} from './land-data.js';
import {CITIES,GOODS} from './data.js';
import {roadQuote,roadSafety,roadToll,roadDays,canServe} from './land.js';
import {shipName,escapeName} from './identity.js';
import {shipSpec,shipDaily} from './industry.js';
import {routeLegs,routeShips,routeSchedule,nextDeparture} from './engine.js';
import {routeAutomation} from './management-view.js';
import {riskFor,RULES} from './security.js';
import {tx,t,nameOf,locale} from './i18n.js';
export const roadTitle=id=>{const r=ROADS[id]??RETIRED_ROADS[id];return `${(CITIES[r.a]??RETIRED_CITIES[r.a]).mapName} ⇄ ${(CITIES[r.b]??RETIRED_CITIES[r.b]).mapName}`;};
export function renderLand(s,{cash,decimal}){
 const level=s.industry.technology.land;
 return `<section class="panel" id="land-panel"><h2>${tx('陸上交易と道路','Land trade and roads')}</h2><p>${tx('馬車は茶色の道路で結ばれた都市間を運行します。巡回では帰路も指定道路でつないでください。港では船と同じ市場で売買します。','Wagons follow brown road links. Every leg, including the return, needs a road. At ports, wagons trade in the same market as ships.')}</p><form id="land-technology"><label>${tx('陸上交易技術','Land trade technology')} ${decimal(level)} · ${tx('維持費軽減','Upkeep reduction')} ${decimal(35*level/(50+level))}%<br>${tx('継続投資（日額）','Daily investment')}<input name="daily" type="number" min="0" step="any" value="${s.industry.investment.land}" required></label><button ${s.gameOver?'disabled':''}>${tx('適用','Apply')}</button></form><p class="small muted">${tx('道路整備と治安投資の効果は逓減します。日額0で停止、資金不足の日は見送ります。改善は次の出発から所要時間に反映します。','Road and safety investment have diminishing returns. Set daily amounts to 0 to stop; unaffordable spending is skipped. New travel times apply on departure.')}</p>
 <div class="crossing-guide"><h3>${tx('海をつなぐ陸上輸送','Overland connections between seas')}</h3><p>${tx('両側の海上ルートと馬車ルートを個別に開設します。港の共通市場で売買して接続するため、貨物の直送や船の陸越えは行いません。運河はありません。','Open separate sea routes on each side and a wagon route between them. They connect by trading in shared port markets, without direct cargo transfer or moving ships overland. There are no canals.')}</p><p>Alexandria ⇄ Cairo ⇄ Suez · ${tx('オスマン帝国','Ottoman Empire')}<br>225 + 150 km · ${tx('地中海と紅海','Mediterranean and Red Sea')}</p><button data-action="open-crossing" data-id="egypt" ${s.gameOver?'disabled':''}>${tx('エジプト陸路を設定','Configure Egypt crossing')}</button><p>Portobelo ⇄ Panama City · ${nameOf({name:'スペイン',nameEn:'Spain'})}<br>100 km · Camino Real · ${tx('カリブ海と太平洋','Caribbean and Pacific')}</p><button data-action="open-crossing" data-id="panama" ${s.gameOver?'disabled':''}>${tx('パナマ陸路を設定','Configure Panama crossing')}</button></div>
 <p class="small muted">${tx('全通過国の免許が必要です。免許取消時は該当ルートを解除し、貨物・道路権・投資を没収、残存馬車を未使用に戻します。','Licenses are required for every transit nation. Revocation removes affected routes, confiscates cargo, road rights and investments, and returns surviving wagons to inventory.')}</p>
 ${Object.entries(ROAD_REGIONS).map(([region,label])=>`<details class="road-region" id="road-region-${region}"><summary>${tx(...label)} · ${Object.values(ROADS).filter(r=>(r.region??'westEurope')===region).length}</summary>${Object.entries(ROADS).filter(([,r])=>(r.region??'westEurope')===region).map(([id,r])=>{const d=s.world.roads[id],q=roadQuote(s,id),owned=d.owner===s.industry.id;return `<details id="road-${id}" class="road-card"><summary>${roadTitle(id)} · ${r.km} km · ${r.terrain==='plain'?tx('平地','Plains'):r.terrain==='hill'?tx('丘陵','Hills'):tx('山地','Mountains')}</summary><p>${tx('馬車の片道日数 / 通行料','Wagon days per leg / toll')}: ${roadDays(s,'wagon',r.a,r.b)} ${t('dayUnit')} / ${cash(roadToll(s,r.a,r.b))}<br>${tx('道路整備度 / 基礎治安 / 実効治安','Road level / base safety / effective safety')}: ${decimal(d.quality)} / ${decimal(r.safety*100)}% / ${decimal(roadSafety(s,r.a,r.b)*100)}%</p><p>${tx('開発権の所有者','Right owner')}: ${owned?tx('自社','Your company'):d.owner==='state'?tx('国家','State'):d.owner==='private'?tx('既存の民間所有者','Private owner'):escapeName(s.competitors.find(c=>c.industry.id===d.owner)?.name??'—')}</p>
 ${owned?`<form class="road-investment" id="road-form-${id}" data-road="${id}"><div class="form-row"><label>${tx('道路整備（日額）','Road improvement per day')}<input name="road" type="number" min="0" max="1000000000000" step="any" value="${d.dailyRoad}" required></label><label>${tx('治安投資（日額）','Safety investment per day')}<input name="security" type="number" min="0" max="1000000000000" step="any" value="${d.dailySecurity}" required></label></div><button ${s.gameOver?'disabled':''}>${tx('適用','Apply')}</button></form><p>${tx('取得原価 / 累計開発投資','Right cost basis / cumulative development investment')}: ${cash(d.basis)} / ${cash(d.invested)}</p>`:`<p>${tx('開発権取得費','Right purchase price')}: ${cash(q.cost)} · ${tx('取得後の資金','Cash after purchase')}: ${cash(s.cash-q.cost)}</p><button data-action="buy-road" data-id="${id}" ${s.gameOver||!q.eligible||s.cash<q.cost?'disabled':''}>${tx('道路開発権を取得','Buy road development right')}</button>${!q.eligible?`<p>${tx('全通過国の交易免許が必要です。','Trading licenses for all transit nations are required.')}</p>`:''}`}</details>`;}).join('')}</details>`).join('')}
 <p class="small muted">${tx('自社所有道路の通行料は免除。他社が支払った通行料の20%を補助収入として受け取ります。民間からの権利購入は割増です。道路整備は地形の影響を軽減しますが、完全には解消しません。','Own roads waive your tolls. Receive 20% of tolls paid by others as supplemental income. Private rights cost more. Improvements reduce terrain penalties without eliminating them.')}</p></section>`;
}
export function renderLandRoute(s,r,{cash,decimal,signed,tone}){
 const fleet=routeShips(s,r),available=s.ships.filter(v=>!v.routeId&&canServe(s,v.type,r)),schedule=routeSchedule(s,r),risk=Math.max(...routeLegs(r).map(([a,b])=>riskFor(s,r,'wagon',a,b).daily));
 return `<article class="route-card"><h3>♞ ${r.stops.map(id=>CITIES[id].mapName).join(' → ')}</h3><p>${tx('馬車','Wagon')}: ${fleet.length} · ${tx('一周','Cycle')} ${schedule.cycle} ${t('dayUnit')} · ${tx('出発間隔','Departure interval')} ${decimal(schedule.interval)} ${t('dayUnit')}</p><div class="route-stats"><div>${t('profit')}<strong class="${tone(r.profit)}">${signed(r.profit)}</strong></div><div>${t('forecast')}<strong>${signed(r.lastForecast)}</strong></div><div>${t('actual')}<strong>${r.lastActual===null?t('notArrived'):signed(r.lastActual)}</strong></div></div>${routeAutomation(r,s,decimal)}
 <label>${tx('契約する陸上護衛','Contracted land escorts')}<select data-escort="${r.id}" ${s.gameOver?'disabled':''}>${[0,1,2,3].map(n=>`<option value="${n}" ${r.escorts===n?'selected':''}>${n} · ${cash(n*RULES.escortDaily)} ${t('daily')}</option>`).join('')}</select></label><p class="small">${tx('1台・1日あたりの最大盗賊襲撃率','Maximum bandit chance per wagon-day')}: ${new Intl.NumberFormat(locale(),{maximumFractionDigits:3}).format(risk*100)}% · ${tx('貨物損失','Cargo loss')}: ${cash(r.losses.cargo)} · ${tx('車両損失','Vehicle loss')}: ${cash(r.losses.ships)}</p><p class="small muted">${tx('護衛は襲撃頻度と被害を軽減します。護衛費は停止中も発生し、輸送利益率には含めません。通行料は輸送利益率に含みます。','Escorts reduce raids and damage. Escort fees continue while paused and are excluded from transport margin; tolls are included.')}</p>
 ${r.pendingReplacements.length?`<p class="warning">${tx('補充待ち','Awaiting replacement')}: ${r.pendingReplacements.length}</p>`:''}<p>${[...new Map(routeLegs(r).map(([a,b])=>[roadBetween(a,b)[0],`${CITIES[a].mapName} ⇄ ${CITIES[b].mapName}: ${cash(roadToll(s,a,b))}`])).values()].join(' / ')}</p><p class="small">${t('margin')}: ${r.minMargin}% · ${r.allowed.map(id=>nameOf(GOODS.find(g=>g.id===id))).join(' / ')}</p><div class="buttons"><button data-action="toggle" data-id="${r.id}" ${s.gameOver?'disabled':''}>${r.active?t('stop'):t('resume')}</button><button data-action="replace-route" data-id="${r.id}" ${s.gameOver?'disabled':''}>${tx('車両を一括置換','Replace vehicles')}</button><button data-action="edit" data-id="${r.id}" ${s.gameOver?'disabled':''}>${t('edit')}</button><button data-action="release" data-id="${r.id}" ${s.gameOver||fleet.some(v=>v.voyage)?'disabled':''}>${tx('ルートを解除','Remove route')}</button></div>
 <form class="assign-form" id="assign-${r.id}" data-route="${r.id}"><label>${tx('未使用車両を追加','Add an idle vehicle')}<select name="ship" required ${available.length?'':'disabled'}>${available.map(v=>`<option value="${v.id}">${escapeName(shipName(s,v))}</option>`).join('')}</select></label><button ${s.gameOver||!available.length?'disabled':''}>${tx('適用','Apply')}</button></form>
 <ul class="fleet-list">${fleet.map(v=>`<li><strong>${escapeName(shipName(s,v))}</strong>  · ${nameOf(shipSpec(s,v.type))}<button data-action="rename-ship" data-id="${v.id}">${tx('名前を変更','Rename vehicle')}</button><button data-action="release-ship" data-id="${v.id}" ${s.gameOver||v.voyage?'disabled':''}>${t('release')}</button><p>${v.voyage?`${CITIES[v.voyage.to].mapName} · ${v.voyage.remaining} ${t('dayUnit')}`:r.active?v.status==='waiting'?t('wait'):`${tx('出発','Departure')} +${nextDeparture(s,r,v)-s.day} ${t('dayUnit')}`:t('stopped')}</p><div class="progress"><span data-voyage-progress="${v.id}" style="width:${v.voyage?100*(v.voyage.total-v.voyage.remaining)/v.voyage.total:0}%"></span></div><p>${t('cargo')}: ${v.cargo.length?v.cargo.map(c=>`${nameOf(GOODS.find(g=>g.id===c.good))} ${c.quantity}`).join(' / '):t('noCargo')} · ${t('upkeep')} ${cash(shipDaily(s,v.type))} ${t('daily')}</p></li>`).join('')}</ul></article>`;
}
