import {shipSpec,shipDaily} from './industry.js';
import { rankings, acquisitionQuote, transportMargin, monthFor, automationShipTypes } from './management.js';
import { SHIPS } from './data.js';
import { operatingProfit } from './engine.js';
import { routeTitle } from './routes-view.js';
import { tx, t, nameOf } from './i18n.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const reasons={
  replaced:['喪失船を補充','Replaced a lost ship'],expanded:['船を購入して増船','Purchased and assigned a ship'],reused:['未使用船を配置','Assigned an idle ship'],shrunk:['1隻を未使用船へ返却','Returned one ship to inventory'],
  cooldown:['調整後の一周分を待機','Waiting one cycle after adjustment'],sample:['一周・到着実績の収集待ち','Waiting for a full cycle and completed voyages'],budget:['月間予算が不足','Monthly budget exhausted'],reserve:['最低保有資金を維持できない','Minimum cash reserve would be breached'],minimumFleet:['最後の1隻は維持','Keeping the last ship'],sailing:['縮小候補の到着待ち','Waiting for a ship to arrive'],threshold:['利益率が閾値内','Margin is within thresholds'],stopped:['ルート停止中','Route is paused'],limit:['保有船の上限','Fleet limit reached'],noOpportunity:['採算・予算を満たす航路なし','No affordable profitable opportunity'],rivalExpanded:['市場を比較して航路を拡張','Expanded after comparing markets'],rivalReassigned:['不採算の待機船を再配置候補へ','Released idle ships from a loss-making service'],acquired:['競合買収を完了','Company acquisition completed'],firstRank:['初めて資産総額1位を達成','Reached first place in assets for the first time']
};
export const reasonText=reason=>tx(...(reasons[reason]??['記録','Record']));
export function renderAutomation(s,{cash}) {
  const a=s.automation,spent=a.month===monthFor(s.day)?a.spent:0;
  const field=(name,label,value,min=0,max=1e12)=>`<label>${label}<input required type="number" name="${name}" min="${min}" max="${max}" step="any" value="${value}" ${s.gameOver?'disabled':''}></label>`;
  return `<section class="panel" id="automation-panel"><h2>${tx('交易網の自動管理','Trade network automation')}</h2><p class="small muted">${tx('設定を適用すると翌日から判定します。利益率が高いルートから増船し、縮小しても最後の1隻は残します。','Settings take effect from the next day. Higher-margin services expand first. Shrinking always keeps one ship.')}</p><form id="automation-form"><label class="checks"><input type="checkbox" name="enabled" ${a.enabled?'checked':''} ${s.gameOver?'disabled':''}>${tx('自動拡大・縮小を有効にする','Enable automatic expansion and contraction')}</label><label class="checks"><input type="checkbox" name="replaceLost" ${a.replaceLost?'checked':''} ${s.gameOver?'disabled':''}>${tx('喪失船を補充する（拡大より先に共通予算を使用）','Replace lost ships (uses shared budget before expansion)')}</label><div class="form-row">${field('monthlyBudget',tx('月間購入予算','Monthly purchase budget'),a.monthlyBudget)}${field('minCash',tx('最低保有資金','Minimum cash reserve'),a.minCash)}</div><div class="form-row">${field('expandThreshold',tx('拡大する利益率（%超）','Expand above margin (%)'),a.expandThreshold,-100,10000)}${field('shrinkThreshold',tx('縮小する利益率（%未満）','Shrink below margin (%)'),a.shrinkThreshold,-100,10000)}</div><button class="primary" ${s.gameOver?'disabled':''}>${tx('自動管理の設定を適用','Apply automation settings')}</button></form><p>${monthFor(s.day)} · ${tx('購入予算使用','Purchase budget used')}: ${cash(spent)} / ${cash(a.monthlyBudget)}</p><p class="small muted">${tx('利益率 =（到着済み貨物の売上 − 仕入・売買税・船の維持費）÷ 同経費。待機中の船の維持費と失った貨物原価・船価も含みます。免許・護衛等の固定費と船購入代は除外します。経費ゼロ・観測不足のときは調整しません。調整後は一周分休止します。','Margin = (completed-cargo sales − purchases, trade taxes and ship upkeep) / those expenses. Waiting-ship upkeep, lost cargo cost and lost ship value are included. Licenses, escort overhead and ship purchases are excluded. Zero expenses or insufficient observations prevent adjustment. Each change is followed by a full-cycle cooldown.')}</p><p class="small muted">${tx('予算と最低資金は自動購入時の制約です。通常の交易・日々の維持費・手動購入には適用されません。各ルートで指定した船種の未使用船を再利用し、なければ購入します。再利用に購入予算は使いませんが、維持費はかかります。','Budget and reserve constrain automatic purchases, not ordinary trading, upkeep or manual purchases. Each route reuses an idle ship of its specified type, or buys that type if none is available. Reuse costs no purchase budget but still incurs upkeep.')}</p><details><summary>${tx('実行・見送り履歴','Decisions and skipped actions')} (${s.managementLog.length})</summary><ol class="management-log">${[...s.managementLog].reverse().slice(0,30).map(e=>`<li>${e.day} ${t('dayUnit')} · ${reasonText(e.reason)}${e.routeId?` · #${e.routeId.split('-')[1]}`:''}${e.cost?` · ${cash(e.cost)}`:''}</li>`).join('')||`<li>${tx('まだ記録はありません。','No decisions yet.')}</li>`}</ol></details></section>`;
}
export function routeAutomation(r,s,decimal) {
  const margin=transportMargin(r),last=[...s.managementLog].reverse().find(e=>e.routeId===r.id);
  const validTypes=automationShipTypes(r,s);const choices=(validTypes.includes(r.autoShipType)?validTypes:[r.autoShipType,...validTypes]).map(type=>`<option value="${type}" ${r.autoShipType===type?'selected':''}>${nameOf(shipSpec(s,type))}${validTypes.includes(type)?'':' · '+tx('航続距離不足','Insufficient range')} · ${tx('積載','Capacity')} ${shipSpec(s,type).capacity} · ¤ ${decimal(shipSpec(s,type).price)}</option>`).join('');
  const selection=`<label>${r.mode==='land'?tx('自動増減用の車両','Vehicle type for automation'):tx('自動増減用の船種','Ship type for automation')}<select name="autoShipType" data-auto-ship="${r.id}" ${s.gameOver?'disabled':''}>${choices}</select></label><p class="small muted">${r.mode==='land'?tx('指定タイプの未使用車両を使い、なければ予算内で購入します。縮小は指定タイプ、次に最小積載量を優先し、移動中は到着を待ちます。','Reuse idle vehicles of the selected type or buy within budget. Shrink that type first, then the smallest capacity, waiting for arrival when needed.'):tx('拡大：指定船種の未使用船を配置。なければ予算・最低資金の範囲で購入。縮小：指定船種を優先し、なければ最小積載量の船を未使用船に戻します。候補が航行中の場合は到着を待ちます。','Expand: assign an idle ship of this type, or buy one within the budget and cash reserve. Shrink: return this type to inventory first, or the lowest-capacity ship if none is assigned. Wait for a candidate to arrive if at sea.')}</p>`;
  return `<div class="automation-route">${selection}<p class="small">${tx('自動調整用の輸送利益率','Transport margin for automation')}: <b>${margin===null?'—':decimal(margin)+'%'}</b> · ${r.transport.since} ${t('dayUnit')} ${tx('以降','onward')} · ${tx('到着','Arrivals')} ${r.transport.deliveries}</p><button data-action="auto-route" data-id="${r.id}" aria-pressed="${r.autoManage}" ${s.gameOver?'disabled':''}>${r.autoManage?tx('自動管理の対象：有効','Automation eligible: on'):tx('自動管理の対象：無効','Automation eligible: off')}</button><p class="small muted">${!s.automation.enabled?tx('会社の自動管理は無効です。','Company automation is disabled.'):last?reasonText(last.reason):tx('判定待ち','Awaiting assessment')}${r.cooldownUntil>s.day?` · ${tx('再調整可能日','Next adjustment day')}: ${r.cooldownUntil}`:''}</p></div>`;
}
export function renderCompetition(s,selected,{cash,signed}) {
  return `<section class="panel competitors"><h2>${tx('資産ランキング・競合会社','Asset ranking and competitors')}</h2><p class="small muted">${tx('資産は現金・船・積み荷・開発権・造船設備の取得原価の合計。同額は同順位です。単独1位の初回達成日を記録し、その後も継続できます。','Assets include cash, ships, cargo, development rights and shipyard facilities at cost. Ties share rank. The first sole lead is recorded; play continues afterward.')}</p>${s.firstRankDay!==null?`<p class="achievement" role="status">⚑ ${tx('初回資産1位','First asset lead')}: ${s.firstRankDay} ${t('dayUnit')}</p>`:''}<ol class="ranking">${rankings(s).map((row,i,rows)=>`<li value="${rows.findIndex(other=>other.assets===row.assets)+1}" class="${row.id==='player'?'player-rank':''}"><strong>${row.id==='player'?escape(s.companyName??tx('あなたの会社','Your company')):escape(row.name)}</strong> ${cash(row.assets)}</li>`).join('')}</ol><p class="small muted">${tx('小規模商人と大規模会社が毎月、市場・航続距離・運営資金を比較して航路と船を増やします。','Small merchants and large companies compare markets, range and operating reserves monthly to select and expand services.')}</p>${s.competitors.map((c,index)=>{const q=acquisitionQuote(s,index),last=c.managementLog.at(-1);return `<div class="competitor ${selected===index?'selected':''}"><h3>${escape(c.name)}</h3><span class="badge">${c.strategy.kind==='large'?tx('大規模交易会社','Large trading company'):tx('小規模商人','Small merchant')}</span><p class="small">${t('cash')} ${cash(c.cash)} · ${t('profit')} ${signed(operatingProfit(c))}<br>${c.ships.length} ${t('ships')} / ${c.routes.length} ${t('routes')} · ${c.gameOver?t('bankrupt'):tx('営業中','Trading')}</p><ul class="small">${c.routes.map(r=>`<li>${routeTitle(r)}</li>`).join('')}</ul><p class="small muted">${last?`${last.day} ${t('dayUnit')} · ${reasonText(last.reason)}`:tx('次の月次判断を待機','Awaiting the next monthly decision')}</p><div class="buttons"><button data-action="select-competitor" data-id="${index}" aria-pressed="${selected===index}">${tx('地図で航路を強調','Highlight route on map')}</button><button data-action="acquire" data-id="${index}" ${s.gameOver||!q.eligible||s.cash<q.required||s.ships.length+c.ships.length>200?'disabled':''}>${tx('買収の詳細','Acquisition details')}</button></div><p class="small muted">${tx('買収代金','Price')} ${cash(q.price)}${q.licenseCost?` + ${tx('不足免許','Missing licenses')} ${cash(q.licenseCost)}`:''}</p></div>`;}).join('')||`<p>${tx('独立した競合会社はありません。','No independent competitors remain.')}</p>`}</section>`;
}
export function renderAcquisition(s,index,cash) {
  const c=s.competitors[index],q=acquisitionQuote(s,index);
  return `<dialog aria-labelledby="acquisition-title"><h2 id="acquisition-title">${escape(c.name)} · ${tx('買収','Acquisition')}</h2><p>${tx('資産評価額の115%（端数切上げ）を買収代金として支払います。不足する免許は通常価格で取得します。','Pay 115% of assessed assets, rounded up. Missing licenses are purchased at normal prices.')}</p><dl><dt>${tx('買収代金','Purchase price')}</dt><dd>${cash(q.price)}</dd><dt>${tx('追加免許費','Additional licenses')}</dt><dd>${cash(q.licenseCost)}</dd><dt>${tx('引き継ぐ現金（負額は債務）','Cash transferred (negative means debt)')}</dt><dd>${cash(q.cash)}</dd><dt>${tx('引き継ぐ船・航路','Ships and services transferred')}</dt><dd>${q.ships} / ${q.routes}</dd><dt>${tx('買収後の保有資金','Cash after acquisition')}</dt><dd>${cash(s.cash-q.price-q.licenseCost+q.cash)}</dd></dl><p class="small muted">${tx('航行中の積み荷・目的地・残日数を維持します。同一経路は統合し、既存ルートの条件を優先します。競合の過去の帳簿は合算せず、買収後の収支を記録します。','Cargo, destinations and remaining travel time are preserved. Matching services merge under your existing policy. Historical accounts are not added to yours; future transactions are recorded normally.')}</p><div class="buttons"><button data-action="cancel">${t('cancel')}</button><button class="primary" data-action="confirm-acquisition" data-id="${index}">${tx('この条件で買収','Acquire on these terms')}</button></div></dialog>`;
}
