import {NATIONS,SHIPS} from './data.js';
import {RULES,licenseTerms,riskFor} from './security.js';
import {routeShips,routeLegs} from './engine.js';
import {tx,t,nameOf,locale} from './i18n.js';
const precise=n=>new Intl.NumberFormat(locale(),{maximumFractionDigits:3}).format(n);
export function eventText(e){
  if(e.kind==='war'||e.kind==='peace')return `${nameOf(NATIONS[e.a])} / ${nameOf(NATIONS[e.b])} · ${e.kind==='war'?tx('開戦','War began'):tx('終戦','Peace agreed')}`;
  const labels={raided:tx('襲撃・積み荷損失','Raid / cargo loss'),shipLost:tx('船を喪失','Ship lost'),warning:tx('免許取消の事前警告','License warning'),revoked:tx('免許取消・ルート解除','License revoked / routes removed'),donation:tx('関係改善への資金投入','Diplomatic contribution'),investmentSkipped:tx('資金不足で継続投資を見送り','Diplomatic investment skipped: insufficient cash')};
  return `${labels[e.kind]}${e.nation?' · '+nameOf(NATIONS[e.nation]):''}${e.routeId?' · #'+e.routeId.split('-')[1]:''}${e.hostile?' · '+tx('国家による妨害','Hostile interception'):''}`;
}
export function renderNotices(s){
  const events=[...s.world.events,...s.incidents].sort((a,b)=>b.day-a.day).filter(e=>s.day-e.day<=30).slice(0,3);
  return events.length?`<section class="warning" aria-label="${tx('情勢・被害通知','World and incident notices')}" role="status">${events.map(e=>`<p>${e.day} ${t('dayUnit')} · ${eventText(e)}</p>`).join('')}</section>`:'';
}
export function routeProtection(s,r,{cash,decimal}){
  const fleet=routeShips(s,r),types=fleet.length?fleet.map(v=>v.type):[r.autoShipType];
  const risk=Math.max(...routeLegs(r).flatMap(([a,b])=>types.map(type=>riskFor(s,r,type,a,b).daily)));
  return `<div class="route-protection"><h3>${tx('航路の保護','Route protection')}</h3><label>${tx('契約する護衛船','Contracted escorts')}<select data-escort="${r.id}" ${s.gameOver?'disabled':''}>${[0,1,2,3].map(n=>`<option value="${n}" ${r.escorts===n?'selected':''}>${n} · ${cash(n*RULES.escortDaily)} ${t('daily')}</option>`).join('')}</select></label><p class="small">${tx('航行1日・1隻あたりの最大襲撃率','Maximum raid chance per sailing ship-day')}: ${precise(risk*100)}% · ${tx('護衛費','Escort cost')}: ${cash(r.escorts*RULES.escortDaily)} ${t('daily')}<br>${tx('商船の砲門数','Merchant guns')}: ${[...new Set(types)].map(type=>`${nameOf(SHIPS[type])} ${SHIPS[type].guns}`).join(' / ')}</p><p class="small muted">${tx('護衛は襲撃頻度と被害を軽減します。砲門数・速度も被害を軽減。護衛費は停止中も発生し、輸送利益率から除外します。','Escorts reduce raid frequency and damage; guns and speed also reduce damage. Escort fees continue while paused and are excluded from transport margin.')}</p><p class="small">${tx('累計被害（貨物原価 / 船価）','Losses to date (cargo cost / ship value)')}: ${cash(r.losses.cargo)} / ${cash(r.losses.ships)} · ${r.losses.count} ${tx('隻喪失','ships lost')}<br>${tx('船喪失も含む航路収支','Route result including ship losses')}: ${cash(r.profit-r.losses.ships)}</p>${r.pendingReplacements.length?`<p class="warning">${tx('補充待ち','Awaiting replacement')}: ${r.pendingReplacements.map(type=>nameOf(SHIPS[type])).join(' / ')}<br>${tx('交易網の自動管理で喪失船の補充を有効にするか、未使用船を追加してください。船が0隻でもルートは維持します。','Enable lost-ship replacement under network automation or add an idle ship. The route remains even with no ships.')}</p>`:''}</div>`;
}
export function renderDiplomacy(s,{cash,decimal}){
  const d=s.diplomacy,disabled=s.gameOver?'disabled':'';
  return `<section class="panel" id="diplomacy-panel"><h2>${tx('外交と海上の安全','Diplomacy and maritime safety')}</h2><p class="small muted">${tx('友好度：初期60 / 免許取得30以上 / 警告35以下 / 取消20以下 / 海上妨害10以下。開戦だけでは免許は取り消されません。敵対国の港から400海里以内の発着港では海上妨害が及びます。取消時は該当ルート全体を解除し、積み荷は補償なしで失い、残存船は未使用船へ戻します。','Friendship: initial 60 / license purchase ≥30 / warning ≤35 / revocation ≤20 / interception ≤10. War alone does not revoke licenses. Interception reaches departure/arrival ports within 400 nm of a hostile port. Revocation removes affected routes, forfeits cargo without compensation, and returns surviving ships to inventory.')}</p>${s.day<=s.world.graceUntil?`<p>${tx('襲撃猶予の終了日','Raid grace ends on day')}: ${s.world.graceUntil}</p>`:''}
    ${Object.entries(NATIONS).map(([id,n])=>{const terms=licenseTerms(s,id),f=d.friendship[id],change=d.lastChange[id];return `<details class="diplomacy-card" id="relations-${id}"><summary><span class="nation-color" style="background:${n.color}"></span>${nameOf(n)} · ${tx('友好度','Friendship')} ${decimal(f)} · ${tx('取消までの余裕','Revocation margin')} ${decimal(f-RULES.revoke)}</summary><p class="small">${tx('前日変化：交易 / 敵国交易 / 投資','Last day: trade / enemy trade / investment')}: +${precise(change.trade)} / ${precise(change.enemies)} / +${precise(change.investment)}<br>${tx('免許取得費 / 維持費 / 税','License fee / upkeep / tax')}: ${cash(terms.fee)} / ${cash(terms.daily)} ${t('daily')} / ${decimal(terms.tax*100)}% · ${terms.canBuy?tx('取得条件を満たす','Eligible'):tx('取得不可','Ineligible')}</p><form class="diplomacy-form" data-nation="${id}" id="diplomacy-${id}"><label>${tx('継続投資（日額）','Daily investment')}<input name="daily" type="number" min="0" max="1000000000000" step="any" value="${d.investment[id]}" required ${disabled}></label><button name="operation" value="daily" ${disabled}>${tx('日額を適用','Apply daily amount')}</button><label>${tx('一時投入額','One-time contribution')}<input name="donation" type="number" min="0" max="1000000000000" step="any" value="1000" ${disabled}></label><button name="operation" value="donation" ${disabled}>${tx('資金を投入','Contribute')}</button></form><p class="small muted">${tx('日額0で停止。継続投資は資金不足なら見送り。1日あたり√日額÷50、即時投入は100につき友好度1（上限100）。投資は資産に計上しません。','Set daily amount to 0 to stop. Unaffordable daily investment is skipped. Daily gain = √amount / 50; contributions gain 1 per 100 (friendship capped at 100). Investment is not an asset.')}</p></details>`;}).join('')}
    <h3>${tx('国家間の関係','Relations between nations')}</h3><p class="small muted">${tx('毎月、国家間友好度が30未満かつ休戦期間終了の組から、距離で補正した確率で開戦します。戦時は武器需要1.8倍、敵国との交易による関係悪化が発生します。','Monthly war rolls require relations below 30 and expired truce; distance adjusts the probability. Wartime weapons demand is 1.8×; trading with an enemy damages friendship.')}</p><ul class="small">${s.world.pairs.map(p=>`<li>${nameOf(NATIONS[p.a])} / ${nameOf(NATIONS[p.b])} · ${decimal(p.relation)} · ${p.until!==null?tx('交戦中','At war'):p.cooldownUntil>s.day?tx('休戦中','Truce'):tx('平時','Peace')}</li>`).join('')}</ul>
    <details id="security-history"><summary>${tx('情勢・被害履歴','World and incident history')}</summary><ol class="management-log">${[...s.world.events,...s.incidents].sort((a,b)=>b.day-a.day).slice(0,60).map(e=>`<li>${e.day} ${t('dayUnit')} · ${eventText(e)}${e.cargoCost!==undefined?' · '+tx('貨物損失','Cargo loss')+' '+cash(e.cargoCost):''}${e.shipValue?' · '+tx('船価損失','Ship loss')+' '+cash(e.shipValue):''}</li>`).join('')||`<li>${tx('まだ記録はありません。','No events yet.')}</li>`}</ol></details></section>`;
}
